version: "3.8"
services:
  user-service:
    image: anasbinesa275/user-service:dev
    ports:
      - "3000:3000"

  product-service:
    image: anasbinesa275/product-service:dev
    ports:
      - "3001:3001"

  order-service:
    image: anasbinesa275/order-service:dev
    ports:
      - "3002:3002"
